name: Deploy feature
on:
  push:
    branches:
      - '**'
      - '!main'
      - '!dependabot/**'


jobs:
  build-deploy:
    name: "Build and deploy to feature"
    permissions:
      contents: "read"
      id-token: "write"
    uses: navikt/bidrag-workflow/.github/workflows/deploy.yaml@chore/deploy_v2
    secrets: inherit