name: Deploy to prod
on:
  push:
    branches:
      - 'main'

jobs:
  build-deploy:
    name: "Build and deploy to prod"
    permissions:
      contents: "write"
      id-token: "write"
    uses: navikt/bidrag-workflow/.github/workflows/deploy_prod.yaml@main
    secrets: inherit

  deploy_unleash:
    runs-on: ubuntu-latest
    name: Deploy unleash
    needs: build-deploy

    steps:
      - uses: actions/checkout@v4
        with:
          path: deploy
      - name: Deploy unleash to prod-gcp
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: deploy/.nais/unleash.yaml
          VARS: deploy/.nais/prod.yaml